spring:
  config:
    activate:
      on-profile: development

application:
  settings:
    openWeatherApi:
      key: 675bf40b4d52b5fb5e47199ec8315931
      weatherUrl: https://api.openweathermap.org/data/2.5/weather
      forecastUrl: https://api.openweathermap.org/data/2.5/forecast
    yandexApi:
      key: X-Yandex-API-Key
      value: 13cd7771-c622-4f86-a1fb-39abad43ce2a
      url: https://api.weather.yandex.ru/v2/informers
    restTemplateProperties:
      connectionTimeout: 3000
      readTimeout: 3000