spring:
  config:
    activate:
      on-profile: development

application:
  settings:
    openWeatherApi:
      key: 675bf40b4d52b5fb5e47199ec8315931
      weatherUrl: https://api.openweathermap.org/data/2.5/weather
      forecastUrl: https://api.openweathermap.org/data/2.5/forecast
    yandexApi:
      key:
      url:
    restTemplateProperties:
      connectionTimeout: 3000
      readTimeout: 3000